sudo: required
services:
  - docker

before_install:
  - docker build -t arjunrm/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run arjunrm/react-test npm test -- --coverage

after_success:
  - docker build -t arjunrm/multi-client ./client
  - docker build -t arjunrm/multi-nginx ./nginx
  - docker build -t arjunrm/multi-server ./server
  - docker build -t arjunrm/multi-worker ./worker

# login to the docker CLI
# setup environment variables using Travis CI DOCKER_ID/DOCKER_PASSWORD
# which will hold encrypted username/password
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# take built images and push them to docker hub
  - docker push arjunrm/multi-client
  - docker push arjunrm/multi-nginx
  - docker push arjunrm/multi-server
  - docker push arjunrm/multi-worker
